site_name: Docs
site_url: https://docs.jdbnet.co.uk
copyright: Copyright &copy; 2023-<script>document.write(new Date().getFullYear())</script> JDB-NET
repo_url: https://github.com/jdbnet/docs
repo_name: jdbnet/docs
theme:
  name: material
  favicon: 'img/favicon.png'
  logo: 'img/favicon.png'
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
  - content.code.copy
  - content.code.select

extra:
  analytics:
    provider: google
    property: G-HX23H5H3QF
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jdbnet
    - icon: fontawesome/brands/mastodon
      link: https://social.jdbnet.co.uk/@jdbnet
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/261595054173323271

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors
  - privacy
  - social