site_name: Docs
site_url: https://docs.jdbnet.co.uk
copyright: Copyright &copy; 2024 JDB-NET
theme:
  name: material
  favicon: 'img/favicon.ico'
  logo: 'img/favicon.ico'
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
  - content.code.copy
  - content.code.select

extra:
  analytics:
    provider: google
    property: G-HX23H5H3QF
